server:
  port: 5000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/menudb
    url: jdbc:mariadb://test-db.c2xjesiqcnrh.ap-northeast-2.rds.amazonaws.com:3306/menudb
    username: swcamp
#    password: swcamp
    password: swcampswcamp

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true